#pragma once

// General
#define FRAMES_PER_SECOND 60 // fps
#define SECONDS_PER_FRAME (1.0f/60) // spf

// Colors
#define PALETTE_1_COLOR_0 0xb2c27d
#define PALETTE_1_COLOR_1 0x739a56
#define PALETTE_1_COLOR_2 0x42665a
#define PALETTE_1_COLOR_3 0x353d46

// Grid
#define TILE_WIDTH 16
#define TILE_HEIGHT 16
#define TILE_ROWS 6
#define TILE_COLUMNS 8
#define TILE_X_START 1
#define TILE_Y_START 3
#define TILE_X_FINAL 8
#define TILE_Y_FINAL 8
#define GRID_WIDTH 128
#define GRID_HEIGHT 96

// Background
#define OFFSET_BACKGROUND_MOVEMENT 50
#define BACKGROUND_ENTITIES 6
#define BIRD_SPEED 30
#define CLOUD1_SPEED 5
#define CLOUD2_SPEED 20
#define CLOUD3_SPEED 15
#define CLOUD4_SPEED 10

// Game
#define MAX_PLANTS_ON_SCREEN 48
#define INIT_SUN_VALUE 100
#define MAX_WAVES 3
#define MAX_ZOMBIES_PER_WAVE 40
#define MAX_AVALIABLE_PLANTS 5
#define MAX_PROJECTILES 70
#define MAX_LEVELS 3

// Sun
#define SUN_VALUE 25
#define SUN_SPEED 5 // fps
#define SUN_MIN_DELAY 7
#define SUN_MAX_DELAY 12
#define MAX_SUN_ON_SCREEN 20

// Projectiles
#define PEA_SPEED 45 // fps

// PEASHOOTER
#define PEASHOOTER_COST 100
#define PEASHOOTER_RECHARGE 450
#define PEASHOOTER_HP 6
#define PEASHOOTER_DAMAGE 1
#define PEASHOOTER_DELAY 90

// SUNFLOWER
#define SUNFLOWER_COST 50
#define SUNFLOWER_RECHARGE 450
#define SUNFLOWER_HP 6
#define SUNFLOWER_DAMAGE 0
#define SUNFLOWER_DELAY 1440

// REPEATER
#define REPEATER_COST 200
#define REPEATER_RECHARGE 450
#define REPEATER_HP 6
#define REPEATER_DAMAGE 1
#define REPEATER_DELAY 90

// WALLNUT
#define WALLNUT_COST 50
#define WALLNUT_RECHARGE 1800
#define WALLNUT_HP 72
#define WALLNUT_DAMAGE 0
#define WALLNUT_DELAY 0

// POTATOMINE
#define POTATOMINE_COST 25
#define POTATOMINE_RECHARGE 1800
#define POTATOMINE_SLEEP_HP 6
#define POTATOMINE_READY_HP 1000
#define POTATOMINE_SLEEP_DAMAGE 0
#define POTATOMINE_READY_DAMAGE 90
#define POTATOMINE_DELAY 900

// ZOMBIE
#define ZOMBIE_HP 10
#define ZOMBIE_DAMAGE 1
#define ZOMBIE_DELAY 60
#define ZOMBIE_SPEED 6
#define NORMAL_ZOMBIE_OFFSET 10

// CONE ZOMBIE
#define CONE_ZOMBIE_HP 28
#define CONE_ZOMBIE_DAMAGE 1
#define CONE_ZOMBIE_DELAY 60
#define CONE_ZOMBIE_SPEED 6
#define CONE_ZOMBIE_OFFSET 17

// BUCKET ZOMBIE
#define BUCKET_ZOMBIE_HP 65
#define BUCKET_ZOMBIE_DAMAGE 1
#define BUCKET_ZOMBIE_DELAY 60
#define BUCKET_ZOMBIE_SPEED 6
#define BUCKET_ZOMBIE_OFFSET 15