#include "sprite.h"

Sprite backgroundSprite = {false, BACKGROUND_WIDTH, BACKGROUND_HEIGHT, 1, 0, 0, 0, 0x4312, {backgroundData}};
Sprite birdSprite = {true, BIRD_WIDTH, BIRD_HEIGHT, BIRD_FRAME_COUNT, BIRD_FRAME_WIDTH, BIRD_FRAME_HEIGHT, BIRD_FPS, 0x4, {birdData}};
Sprite cloud1Sprite = { false, CLOUD1_WIDTH, CLOUD1_HEIGHT, 1, 0, 0, 0, 0x04, {cloud1Data}};
Sprite cloud2Sprite = { false, CLOUD2_WIDTH, CLOUD2_HEIGHT, 1, 0, 0, 0, 0x40, {cloud2Data}};
Sprite cloud3Sprite = { false, CLOUD3_WIDTH, CLOUD3_HEIGHT, 1, 0, 0, 0, 0x40, {cloud3Data}};
Sprite cloud4Sprite = { false, CLOUD4_WIDTH, CLOUD4_HEIGHT, 1, 0, 0, 0, 0x40, {cloud4Data}};

Sprite sunSprite = {true, SUN_WIDTH, SUN_HEIGHT, SUN_FRAME_COUNT, SUN_FRAME_WIDTH, SUN_FRAME_HEIGHT, SUN_FPS, 0x2310, {sunData}};
Sprite uiSprite = {false, UI_WIDTH, UI_HEIGHT, 1, 0, 0, 0, 0x1243, {uiData}};

Sprite peashooterSprite = {true, PEASHOOTER_WIDTH, PEASHOOTER_HEIGHT, PEASHOOTER_FRAME_COUNT, PEASHOOTER_FRAME_WIDTH, PEASHOOTER_FRAME_HEIGHT, PEASHOOTER_FPS, 0x2340, {peashooterData}};
Sprite sunflowerSprite = {true, SUNFLOWER_WIDTH, SUNFLOWER_HEIGHT,SUNFLOWER_FRAME_COUNT, SUNFLOWER_FRAME_WIDTH, SUNFLOWER_FRAME_HEIGHT, SUNFLOWER_FPS, 0x2140, {sunflowerData}};

Sprite repeaterSprite = {true, REPEATER_WIDTH, REPEATER_HEIGHT, REPEATER_FRAME_COUNT, REPEATER_FRAME_WIDTH, REPEATER_FRAME_HEIGHT, REPEATER_FPS, 0x2340, {repeaterData}};
Sprite wallnutSprite = {true, WALLNUT_WIDTH, WALLNUT_HEIGHT, WALLNUT_FRAME_COUNT, WALLNUT_FRAME_WIDTH, WALLNUT_FRAME_HEIGHT, WALLNUT_FPS, 0x1240, {wallnutData}};
Sprite potatomineSleepSprite = {true, POTATOMINE_WIDTH, POTATOMINE_HEIGHT, POTATOMINE_FRAME_COUNT, POTATOMINE_FRAME_WIDTH, POTATOMINE_FRAME_HEIGHT, POTATOMINE_FPS, 0x4230, {potatomineSleepData}};
Sprite potatomineReadySprite = {true, POTATOMINE_WIDTH, POTATOMINE_HEIGHT, POTATOMINE_FRAME_COUNT, POTATOMINE_FRAME_WIDTH, POTATOMINE_FRAME_HEIGHT, POTATOMINE_FPS, 0x4230, {potatomineReadyData}};

Sprite zombieSprite = {true, ZOMBIE_WIDTH, ZOMBIE_HEIGHT, ZOMBIE_FRAME_COUNT, ZOMBIE_FRAME_WIDTH, ZOMBIE_FRAME_HEIGHT, ZOMBIE_FPS, 0x1240, {zombieData}};
Sprite zombieAttackingSprite = {true, ZOMBIE_WIDTH, ZOMBIE_HEIGHT, ZOMBIE_FRAME_COUNT, ZOMBIE_FRAME_WIDTH, ZOMBIE_FRAME_HEIGHT, ZOMBIE_FPS, 0x1240, {zombieAttackingData}};
Sprite coneZombieSprite = {true, CONE_ZOMBIE_WIDTH, CONE_ZOMBIE_HEIGHT, CONE_ZOMBIE_FRAME_COUNT, CONE_ZOMBIE_FRAME_WIDTH, CONE_ZOMBIE_FRAME_HEIGHT, CONE_ZOMBIE_FPS, 0x1240, {coneZombieData}};
Sprite coneZombieAttackingSprite = {true, CONE_ZOMBIE_WIDTH, CONE_ZOMBIE_HEIGHT, CONE_ZOMBIE_FRAME_COUNT, CONE_ZOMBIE_FRAME_WIDTH, CONE_ZOMBIE_FRAME_HEIGHT, CONE_ZOMBIE_FPS, 0x1240, {coneZombieAttackingData}};
Sprite bucketZombieSprite = {true, BUCKET_ZOMBIE_WIDTH, BUCKET_ZOMBIE_HEIGHT, BUCKET_ZOMBIE_FRAME_COUNT, BUCKET_ZOMBIE_FRAME_WIDTH, BUCKET_ZOMBIE_FRAME_HEIGHT, BUCKET_ZOMBIE_FPS, 0x1240, {bucketZombieData}};
Sprite bucketZombieAttackingSprite = {true, BUCKET_ZOMBIE_WIDTH, BUCKET_ZOMBIE_HEIGHT, BUCKET_ZOMBIE_FRAME_COUNT, BUCKET_ZOMBIE_FRAME_WIDTH, BUCKET_ZOMBIE_FRAME_HEIGHT, BUCKET_ZOMBIE_FPS, 0x1240, {bucketZombieAttackingData}};

Sprite levelCompletedSprite = {false, LEVEL_COMPLETED_WIDTH, LEVEL_COMPLETED_HEIGHT, 1, 0, 0, 0, 0x140, {levelCompletedData}};
Sprite winSprite = {false, WIN_WIDTH, WIN_HEIGHT, 1, 0, 0, 0, 0x40, {winData}};
Sprite startSprite = {false, START_WIDTH, START_HEIGHT, 1, 0, 0, 0, 0x140, {startData}};
Sprite gameOverSprite = {false, GAME_OVER_WIDTH, GAME_OVER_HEIGHT, 1, 0, 0, 0, 0x140, {gameOverData}};

Sprite peaSprite = {false, PEA_WIDTH, PEA_HEIGHT, 1, PEA_WIDTH, PEA_HEIGHT, 1, 0x3140, {peaData}};